# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 12:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
